### ISSUE TITLE
Uncaught Amp\MultiReasonException: onStart observer initialization failure.

### ISSUE THREAD

**Issue by juzi5201314** [amphp/http-server#295]
This my code:
```
<?php

require_once __DIR__."/vendor/autoload.php";

use Amp\Http\Server\Server as HttpServer;
use Amp\Http\Server\Router;
use function Amp\Socket\listen;

use Amp\Loop;

use Psr\Log\NullLogger;

Loop::run(function () {
    $router = new Router();
    $server = new HttpServer([listen('0.0.0.0:7000')], $router, new NullLogger());

    yield $server->start();

    Loop::onSignal(\SIGINT, static function (string $watcherId) use ($server) {
        Loop::cancel($watcherId);
        yield $server->stop();
    });
});
```
run `php main.php`:

```
Fatal error: Uncaught Amp\MultiReasonException: onStart observer initialization failure in /home/soeur/PhpstormProjects/ppbed/vendor/amphp/http-server/src/Server.php:303
Stack trace:
#0 [internal function]: Amp\Http\Server\Server->doStart()
#1 /home/soeur/PhpstormProjects/ppbed/vendor/amphp/amp/lib/Coroutine.php(105): Generator->send(Array)
#2 /home/soeur/PhpstormProjects/ppbed/vendor/amphp/amp/lib/Internal/Placeholder.php(43): Amp\Coroutine->Amp\{closure}(NULL, Array)
#3 /home/soeur/PhpstormProjects/ppbed/vendor/amphp/amp/lib/Internal/PrivatePromise.php(23): class@anonymous->onResolve(Object(Closure))
#4 /home/soeur/PhpstormProjects/ppbed/vendor/amphp/amp/lib/Coroutine.php(138): Amp\Internal\PrivatePromise->onResolve(Object(Closure))
#5 /home/soeur/PhpstormProjects/ppbed/vendor/amphp/http-server/src/Server.php(266): Amp\Coroutine->__construct(Object(Generator))
#6 /home/soeur/PhpstormProjects/ppbed/main.php(17): Amp\Http\Server\Server->start()
#7 [internal function]: {closure}('a', NULL)
PHP Fatal error:  Uncaught Amp\MultiReasonException: onStart observer initialization failure in /home/soeur/PhpstormProjects/ppbed/vendor/amphp/http-server/src/Server.php:303
#8 /home/soeur/PhpstormProjects/p in /home/soeur/PhpstormProjects/ppbed/vendor/amphp/http-server/src/Server.php on line 303
```

**Comment by kelunik** [comment]
Please also dump the actual reasons, so catch the exception and dump `$e->getReasons()`.

**Comment by juzi5201314** [comment]
ok. I found the cause of the problem:
`Router start failure: no routes registered`
But there is no warning in the router repository, there must be a route, otherwise it will report an error......

**Comment by juzi5201314** [comment]
And I want to ask casually if there are asynchronous non-blocking file operations.  I found [amphp/file](https://github.com/amphp/file)  but it doesn't have any documentation and examples.
What is the correct usage of the library? Or should I go to this repository to initiate a new issue?

**Comment by kelunik** [comment]
amphp/file is what you should use, yes. The main API are the functions in https://github.com/amphp/file/blob/master/src/functions.php, and if you open a file handle, look at the file interface for possible operations.

PR for examples welcome.

**Comment by juzi5201314** [comment]
Haha ok i know.
